version: "3.8"

services:
  localstack:
    container_name: sleuth-localstack
    build: "./localstack"
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - AWS_ACCESS_KEY_ID=x
      - AWS_SECRET_ACCESS_KEY=x
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - sleuth

networks:
  sleuth: